project:
  type: website
  output-dir: _site

execute:
  enabled: true
  freeze: true
  
engine: knitr
 
website:
  title: "Huber Group @ EMBL"
  open-graph:
     locale:
       en_US
     site-name:
       "Huber Group @ EMBL"
  navbar:
    background: "#18974C"
    foreground: "#D0DEBB"
    search: true
    left:
      - href: index.html
        text: Home
  favicon: resources/favicon.png
 
format:
  html:
    theme:
      - materia
    linkcolor: "#2A57A3"
    toc-color: "#2A57A3"
    toc: true
    grid:
      sidebar-width: 150px
      body-width: 750px
      margin-width: 300px
    date-format: iso
    include-in-header:
      - text: |
          <meta http-equiv="Cache-Control" content="max-age=1800, must-revalidate"> 
    lightbox: true
    
# 
# EMBL colors: https://www.embl.org/guidelines/design/design-guidelines/colours/
