services:
  - type: web
    name: oauth2-proxy-render
    plan: free
    env: docker
    envVars:
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECRET
        generateValue: true
      - key: OAUTH2_PROXY_REDIRECT_URL
        value: "https://intercept-test.onrender.com/oauth2/callback"
      - key: PORT
        value: "10000" # Render's default port for web services