services:
  - type: web
    name: static-site
    plan: free
    repo: https://github.com/Huber-group-EMBL/INTeRCePT-Data-Management
    startCommand: |
      # Serve the static site from the _site folder using Python HTTP server
      python3 -m http.server --directory _site 8000
    runtime: python
  - type: web
    name: oauth2-proxy
    plan: free
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0  # Pre-built Docker image
    envVars:
      - key: UPSTREAM
        fromService:
          name: static-site
          type: web
          property: hostport
      - key: OAUTH2_PROXY_PROVIDER
        sync: false
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECRET
        generateValue: true
      - key: OAUTH2_PROXY_EMAIL_DOMAINS
        value: '*'
      - key: OAUTH2_PROXY_HTTP_ADDRESS
        value: ":4180"
